# Generated by Django 5.2.5 on 2025-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
