# Generated by Django 5.2.5 on 2025-08-22 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0002_deposittransaction_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('50.0'))]),
        ),
    ]
