# Generated by Django 5.2.5 on 2025-08-23 15:10

import django.db.models.deletion
import investment_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0003_userinvestment_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Verified'), ('rejected', 'Rejected'), ('additional_info', 'Additional Information Required')], default='pending', max_length=20)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'National ID Card'), ('driving_license', 'Driving License')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_front', models.ImageField(upload_to=investment_app.models.user_kyc_path)),
                ('document_back', models.ImageField(blank=True, null=True, upload_to=investment_app.models.user_kyc_path)),
                ('selfie_with_document', models.ImageField(upload_to=investment_app.models.user_kyc_path)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
    ]
