# Generated by Django 5.2.5 on 2025-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0005_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USDT(TRC20)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USDT(TRC20)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='min_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USDT(TRC20)'), ('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)')], max_length=10),
        ),
    ]
