# Generated by Django 5.2.5 on 2025-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0006_alter_cryptowallet_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='last_yield_calculation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='next_yield_calculation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
